services:
  client:
    build:
      context: ./
      dockerfile: ./app_client/Dockerfile
    ports:
      - 3000:3000
    networks:
      - a_level_exam
  db:
    image: mongo:7.0
    ports:
      - 27017:27017
    networks:
      - a_level_exam
  server:
    # env_file: ".env"
    build:
      context: ./
      dockerfile: ./app_server/Dockerfile
    ports:
      - 8000:8000
    networks:
      - a_level_exam
    depends_on:
      - db

  model_h_1:
    build:
      context: ./
      dockerfile: app_model_l/Dockerfile
    volumes:
      - ./app_model_l/weights:/app_model/weights
    ports:
      - 8001:8000
    networks:
      - a_level_exam

  model_h_2:
    build:
      context: ./
      dockerfile: app_model_l/Dockerfile
    volumes:
      - ./app_model_l/weights:/app_model/weights
    ports:
      - 8003:8000
    networks:
      - a_level_exam

  model_l:
    build:
      context: ./
      dockerfile: app_model_l/Dockerfile
    volumes:
      - ./app_model_l/weights:/app_model/weights
    ports:
      - 8002:8000
    networks:
      - a_level_exam


networks:
  a_level_exam:
    driver: bridge
