name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - newbackend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

        

      - name: Execute tests in the running services
        run: |
          cd app_server
          sudo apt install python3-pip
          pip install -r requirements.txt
          pytest
